### ISSUE TITLE
Request for documentation: Multipart Uploading

### ISSUE THREAD

**Issue by cswkim** [nftstorage/python-client#3]
I see an example for uploading a single file as a binary stream using the `.store()` method, but could there be an example added to the documentation around `multipart/form-data`? OpenAPI is generating the documentation correct? Can you send files with other mimetypes besides images, such as mp4, json ,etc.? Are there limits to the number of files one can upload at once? I believe there is a limitation of 100MB per request in terms of the batch size?

The `body` parameter for `store()` requires a type of `IOBase`, I know in some other libraries like `requests` you send a files `dict` in the format:

```python
{
  'name': ('filename.mp4', open('path/to/file', 'rb'), 'video/mp4'),
  'othername': ('otherfilename.mp4', open('path/to/otherfile', 'rb'), 'video/mp4'),
}
```

Is the `Content-Type: multipart/form-data` header going to be automatically set or do you have to manually pass that in somewhere?

Apologies if this issue is more suited for a platform like StackOverflow, if so please close and I will move this question there.

**Comment by yusefnapora** [comment]
Hi, thanks for opening this - I don't have a ton of experience with the python client but scanning through the code it looks like the OpenAPI generator might not be smart enough to figure out that the `/upload` endpoint supports both POSTing the file body directly and sending multi-part form data.

For now it may be simplest to bypass the client and use `requests` or a similar lib to send a multipart form request to `/upload`. The [HTTP API docs](https://nft.storage/api-docs/) should help with making the request.

It might also be possible for us to tweak the schema so that it generates a separate client method for the multiple file case. I'll make an issue for that in the main nft.storage repo to keep track of this and other issues with the generated client.

**Comment by cswkim** [comment]
Thanks for your response @yusefnapora. I think I've seen some other OpenAPI implementations that do in fact have a separate method, something like `make_multipart()` that specifically handles multi-part form data.

I ended up using the good 'ol `requests` library which works great and is pretty simple to implement a multi-file POST.
